// ──────────────────────────────────────────────────────────────────────
// LUMEN — Claude-direct, deliberately NOT routed through Vercel AI Gateway.
// Decision (Jun 2026): Lumen is a Claude-focused feature. Its multi-turn +
// tool-using shape (LUMEN_TOOLS) benefits from the Anthropic SDK directly
// and from Claude-specific affordances (deep tool-call fidelity, computer
// use, future prompt caching). Reasoning routes that DO go through Gateway:
// persona-generation, target-role-mapping, mapping-suggestions.
// Don't migrate this route to gateway without explicit product approval.
// ──────────────────────────────────────────────────────────────────────
import { NextRequest } from "next/server";
import { getSessionUser } from "@/lib/auth";
import { getSetting } from "@/lib/settings";
import { reportError } from "@/lib/monitoring";
import { checkAIRate } from "@/lib/rate-limit-middleware";
import { getDashboardStats } from "@/lib/queries";
import { getUserScope, getUserScopeDepartments } from "@/lib/scope";
import { db } from "@/db";
import * as schema from "@/db/schema";
import { inArray, sql } from "drizzle-orm";
import Anthropic from "@anthropic-ai/sdk";
import { LUMEN_TOOLS, executeTool } from "@/lib/assistant/tools";
import { buildRagContext } from "@/lib/assistant/rag-context";

export const dynamic = "force-dynamic";
export const maxDuration = 60;

interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

interface ChatRequestBody {
  message: string;
  history: ChatMessage[];
  context: {
    page: string;
    userRole: string;
    userName: string;
  };
}

async function getLumenDataContext(user: { id: number; role: string; organizationId: number }): Promise<string> {
  try {
    const orgId = user.organizationId;
    const stats = await getDashboardStats(orgId);
    const scopedUserIds = await getUserScope(user as Parameters<typeof getUserScope>[0]);
    const scopeDepts = await getUserScopeDepartments(user as Parameters<typeof getUserScopeDepartments>[0]);

    const lines: string[] = [
      `\n## Current Project Data`,
      `- Total users: ${stats.totalUsers} (${stats.totalSourceRoles} source roles, ${stats.totalTargetRoles} target roles)`,
      `- Personas: ${stats.totalPersonas} generated, ${stats.totalGroups} consolidated groups`,
      `- Persona coverage: ${stats.usersWithPersona}/${stats.totalUsers} users assigned (${stats.totalUsers > 0 ? Math.round((stats.usersWithPersona / stats.totalUsers) * 100) : 0}%)`,
      `- Mapped: ${stats.personasWithMapping}/${stats.totalPersonas} personas have target role assignments`,
      `- Approved: ${stats.approvedAssignments}/${stats.totalAssignments} assignments approved`,
      `- SOD rules: ${stats.sodRulesCount} loaded`,
    ];

    const conflicts = stats.sodConflictsBySeverity;
    if (conflicts.length > 0) {
      lines.push(`- SOD conflicts: ${conflicts.map(c => `${c.count} ${c.severity}`).join(", ")}`);
    }
    if (stats.lowConfidence > 0) {
      lines.push(`- Low confidence assignments: ${stats.lowConfidence}`);
    }

    // Scoped context for non-admin roles
    if (scopedUserIds !== null) {
      lines.push(`\n## Your Scope`);
      lines.push(`- Departments: ${scopeDepts && scopeDepts.length > 0 ? scopeDepts.join(", ") : "None assigned"}`);
      lines.push(`- Users in your scope: ${scopedUserIds.length}`);

      if (scopedUserIds.length > 0) {
        const [scopedPersonaCountRow] = await db
          .select({ count: sql<number>`count(distinct persona_id)` })
          .from(schema.userPersonaAssignments)
          .where(inArray(schema.userPersonaAssignments.userId, scopedUserIds));
        const scopedPersonaCount = scopedPersonaCountRow?.count ?? 0;
        lines.push(`- Personas in your scope: ${scopedPersonaCount}`);
      }
    }

    return lines.join("\n");
  } catch {
    return "\n## Project Data\nUnable to load project statistics.";
  }
}

function buildSystemPrompt(userName: string, userRole: string, page: string, dataContext: string): string {
  return `You are Lumen, the Provisum AI assistant for enterprise security role mapping.

You are speaking with ${userName} (role: ${userRole}). They are currently on the "${page}" page.
${dataContext}

Key platform concepts:
- **Personas**: Groups of users with similar access patterns, generated by AI analysis.
- **SOD Conflicts**: Segregation of Duties violations where incompatible permissions are assigned.
- **Target Roles**: Destination roles in the new system that source permissions map to.
- **Approval Workflow**: Mapper submits -> Approver reviews -> Coordinator oversees.
- **Provisioning Alerts**: Flags for users with more access than needed.

You have access to tools that can query live project data and trigger actions. Use them proactively when the user asks about data, numbers, statuses, or wants to start operations. Do not just rely on the summary data above — call the appropriate tool to get fresh, detailed data.

For action tools (trigger_auto_map, trigger_sod_analysis): these create background jobs. Always confirm the action with the user by describing what will happen. Only users with mapper, admin, or system_admin roles can trigger actions.

Guidelines:
- Be concise and action-oriented. Use the project data above to give specific, quantified answers.
- When a user asks "how many", "what's left", or "what's the status" — use your tools to get the latest numbers.
- Respect the user's role boundaries. A viewer should not be guided to perform admin actions.
- If asked about something outside the platform, politely redirect.
- Use markdown sparingly — bold for emphasis, bullet lists for steps.
- Reference pages by name: Dashboard, Personas, Role Mapping, SOD Analysis, Approvals, Exports.`;
}

export async function POST(req: NextRequest) {
  const user = await getSessionUser();
  if (!user) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401,
      headers: { "Content-Type": "application/json" },
    });
  }

  // Rate limit: 10 AI requests per minute per user
  const rateLimited = await checkAIRate(req, String(user.id));
  if (rateLimited) return rateLimited;

  let body: ChatRequestBody;
  try {
    body = await req.json();
  } catch {
    return new Response(JSON.stringify({ error: "Invalid request body" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const { message, history = [], context } = body;

  if (!message || typeof message !== "string") {
    return new Response(JSON.stringify({ error: "Message is required" }), {
      status: 400,
      headers: { "Content-Type": "application/json" },
    });
  }

  const apiKey = await getSetting("ai.apiKey") || process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return new Response(JSON.stringify({ error: "AI API key not configured" }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }

  const model = await getSetting("ai.model") || "claude-sonnet-4-20250514";

  const dataContext = await getLumenDataContext(user);
  const ragContext = buildRagContext(message, context?.page || "unknown");
  const systemPrompt = buildSystemPrompt(
    context?.userName || user.displayName,
    context?.userRole || user.role,
    context?.page || "unknown",
    dataContext + ragContext
  );

  const messages: Anthropic.MessageParam[] = [
    ...history.map((msg) => ({
      role: msg.role as "user" | "assistant",
      content: msg.content,
    })),
    { role: "user" as const, content: message },
  ];

  try {
    const client = new Anthropic({ apiKey });

    // We need to handle a tool-use loop: Claude may request tool calls,
    // we execute them, send results back, and Claude gives a final text answer.
    // We stream only the final text response to the client.
    // To show progress, we send SSE events for tool-use status and streamed text.

    const encoder = new TextEncoder();

    const readableStream = new ReadableStream({
      async start(controller) {
        try {
          let conversationMessages = [...messages];
          let toolCallCount = 0;
          const MAX_TOOL_CALLS = 3;

          // Loop: call Claude, handle tool use, repeat until we get text or hit limit
          while (toolCallCount < MAX_TOOL_CALLS) {
            const response = await client.messages.create({
              model,
              max_tokens: 2048,
              system: systemPrompt,
              messages: conversationMessages,
              tools: LUMEN_TOOLS,
            });

            // Check if response has tool_use blocks
            const toolUseBlocks = response.content.filter(
              (block): block is Anthropic.ContentBlock & { type: "tool_use" } =>
                block.type === "tool_use",
            );
            const textBlocks = response.content.filter(
              (block): block is Anthropic.ContentBlock & { type: "text" } =>
                block.type === "text",
            );

            if (toolUseBlocks.length === 0) {
              // No tool calls — stream any text blocks and finish
              for (const block of textBlocks) {
                controller.enqueue(
                  encoder.encode(`data: ${JSON.stringify({ text: block.text })}\n\n`),
                );
              }
              controller.enqueue(encoder.encode("data: [DONE]\n\n"));
              controller.close();
              return;
            }

            // There are tool calls to execute
            // First, send any leading text
            for (const block of textBlocks) {
              controller.enqueue(
                encoder.encode(`data: ${JSON.stringify({ text: block.text })}\n\n`),
              );
            }

            // Send tool-use status events to the client
            for (const toolBlock of toolUseBlocks) {
              const statusLabel = getToolStatusLabel(toolBlock.name);
              controller.enqueue(
                encoder.encode(
                  `data: ${JSON.stringify({ tool_status: statusLabel, tool_name: toolBlock.name })}\n\n`,
                ),
              );
            }

            // Execute all tool calls and collect results
            const toolResults: Anthropic.ToolResultBlockParam[] = [];
            for (const toolBlock of toolUseBlocks) {
              const result = await executeTool(
                toolBlock.name,
                (toolBlock.input as Record<string, unknown>) || {},
                user,
              );
              toolResults.push({
                type: "tool_result",
                tool_use_id: toolBlock.id,
                content: result,
              });
              toolCallCount++;
            }

            // Add the assistant's response and tool results to the conversation
            conversationMessages = [
              ...conversationMessages,
              { role: "assistant" as const, content: response.content },
              { role: "user" as const, content: toolResults },
            ];
          }

          // If we exhausted tool call limit, do a final non-tool call to get text
          const finalResponse = await client.messages.create({
            model,
            max_tokens: 2048,
            system: systemPrompt,
            messages: conversationMessages,
            // No tools — force a text response
          });

          for (const block of finalResponse.content) {
            if (block.type === "text") {
              controller.enqueue(
                encoder.encode(`data: ${JSON.stringify({ text: block.text })}\n\n`),
              );
            }
          }

          controller.enqueue(encoder.encode("data: [DONE]\n\n"));
          controller.close();
        } catch (error) {
          reportError(error, { source: "chat-api", phase: "tool-loop" });
          controller.enqueue(
            encoder.encode(
              `data: ${JSON.stringify({ error: "Something went wrong while processing your request." })}\n\n`,
            ),
          );
          controller.enqueue(encoder.encode("data: [DONE]\n\n"));
          controller.close();
        }
      },
    });

    return new Response(readableStream, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
      },
    });
  } catch (error) {
    reportError(error, { source: "chat-api" });
    return new Response(
      JSON.stringify({ error: "Failed to connect to AI service" }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}

// ---------------------------------------------------------------------------
// Human-readable status labels for tool calls
// ---------------------------------------------------------------------------

function getToolStatusLabel(toolName: string): string {
  switch (toolName) {
    case "get_dashboard_stats":
      return "Checking dashboard data...";
    case "get_persona_details":
      return "Looking up persona details...";
    case "get_sod_conflicts":
      return "Analyzing SOD conflicts...";
    case "get_mapping_status":
      return "Checking mapping progress...";
    case "trigger_auto_map":
      return "Starting auto-mapping...";
    case "trigger_sod_analysis":
      return "Running SOD analysis...";
    case "get_job_status":
      return "Checking job status...";
    case "get_calibration_summary":
      return "Reviewing confidence data...";
    case "create_role_mapping":
      return "Creating role mapping...";
    case "resolve_sod_conflict":
      return "Resolving SOD conflict...";
    case "accept_calibration_items":
      return "Accepting calibration items...";
    case "submit_for_review":
      return "Submitting assignments for review...";
    case "send_reminder":
      return "Sending reminder notifications...";
    default:
      return "Processing...";
  }
}
